root = "."
testdata_dir = "testdata"
[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
include_ext = ["go", "tpl", "html"]
exclude_dir = ["dist", "tmp", "vendor", ".git"]
exclude_patterns = ["*_test.go"]
[log]
  time = "2006-01-02 15:04:05"
  color = true
